/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.6.1
 * source: brambl/models/evidence.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../../validate/validate";
import * as dependency_2 from "./../../quivr/models/shared";
import * as pb_1 from "google-protobuf";
export namespace co.topl.brambl.models {
    export class Evidence extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            digest?: dependency_2.quivr.models.Digest;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("digest" in data && data.digest != undefined) {
                    this.digest = data.digest;
                }
            }
        }
        get digest() {
            return pb_1.Message.getWrapperField(this, dependency_2.quivr.models.Digest, 1) as dependency_2.quivr.models.Digest;
        }
        set digest(value: dependency_2.quivr.models.Digest) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        get has_digest() {
            return pb_1.Message.getField(this, 1) != null;
        }
        static fromObject(data: {
            digest?: ReturnType<typeof dependency_2.quivr.models.Digest.prototype.toObject>;
        }): Evidence {
            const message = new Evidence({});
            if (data.digest != null) {
                message.digest = dependency_2.quivr.models.Digest.fromObject(data.digest);
            }
            return message;
        }
        toObject() {
            const data: {
                digest?: ReturnType<typeof dependency_2.quivr.models.Digest.prototype.toObject>;
            } = {};
            if (this.digest != null) {
                data.digest = this.digest.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_digest)
                writer.writeMessage(1, this.digest, () => this.digest.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Evidence {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Evidence();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.digest, () => message.digest = dependency_2.quivr.models.Digest.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Evidence {
            return Evidence.deserialize(bytes);
        }
    }
}
